
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: nakagawahiroki
  port: 5432
  password: postgres

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manage_money_development


test:
  <<: *default
  database: manage_money_test


production:
  adapter: postgresql
  encoding: unicode
  host: aws-infra-web.cxeexjjytkfx.ap-northeast-1.rds.amazonaws.com
  user: nakagawa
  port: 5432
  database: manage_money_production
  password: nh10221022
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

